projects:
  audacity:
    git_url: "https://github.com/audacity/audacity.git"
    actions:
      - "build.yml"
  juiceshop:
    git_url: "https://github.com/miguelmemm16/juiceshop.git"
    actions:
      - "ci.yml"