projects:
  audacity:
    git_url: "https://github.com/audacity/audacity.git"
    actions:
      - "build.yml"
  cloudWeatherAPI:
    git_url: "https://github.com/iiTONELOC/cloudyWeatherAPI"
    actions:
      - "main_cloudyweatherapi.yml"
  dgs-framework:
    git_url: "https://github.com/Netflix/dgs-framework"
  django-api:
    git_url: "https://github.com/awaisanjumx2/django-api"
    actions:
      - "main_djangowebapi.yml"
  juiceshop:
    git_url: "https://github.com/miguelmemm16/juiceshop.git"
    actions:
      - "ci.yml"
  tailwindcss:
    git_url: "https://github.com/tailwindlabs/tailwindcss"
  tsdownsample:
    git_url: "https://github.com/predict-idlab/tsdownsample"