projects:
  audacity:
    git_url: "https://github.com/audacity/audacity"
    branch: "master"
    actions:
      - name: "build.yml"
        parsers:
          intra: ["github_up_down"]

  juiceshop:
    git_url: "https://github.com/miguelmemm16/juiceshop"
    branch: "develop"
    actions:
      - name: "ci.yml"
        parsers:
          intra: ["github_up_down"]