projects:
  audacity:
    git_url: "https://github.com/audacity/audacity.git"
    actions:
      - name: "build.yml"
        # parsers:
          # intra: ["github_up_down"]
          # inter: ["needs"]

  juiceshop:
    git_url: "https://github.com/miguelmemm16/juiceshop.git"
    actions:
      - name: "ci.yml"
        # parsers:
          # intra: ["github_up_down"]
          # inter: ["needs"]